# Generated by Django 3.2.13 on 2022-06-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kocoonBackendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
