# Generated by Django 3.2.13 on 2022-07-16 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kocoonBackendApp', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Meeting', max_length=100)),
                ('zoom_link', models.URLField()),
                ('meeting_type', models.CharField(choices=[('Private', 'Private'), ('Group', 'Group'), ('OH', 'Oh')], default='Private', max_length=10)),
                ('meeting_host', models.CharField(default='', max_length=50)),
                ('meeting_time', models.DateTimeField()),
                ('meeting_status', models.CharField(choices=[('Passed', 'Passed'), ('Upcoming', 'Upcoming'), ('Occurring', 'Occurring')], default='Upcoming', max_length=10)),
                ('meeting_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('topics_discussed', models.CharField(default='', max_length=200)),
                ('notes', models.CharField(default='', max_length=400)),
                ('attendees', models.ManyToManyField(related_name='meetings', to='kocoonBackendApp.UserProfileInfo')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kocoonBackendApp.userprofileinfo')),
            ],
        ),
    ]
